// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen6.h"
#include "screens/ui_Screen7.h"
#include "screens/ui_Screen8.h"
#include "screens/ui_Screen5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_road2_png);    // assets/road2.png
LV_IMG_DECLARE(ui_img_left_png);    // assets/Left.png
LV_IMG_DECLARE(ui_img_right_png);    // assets/Right.png
LV_IMG_DECLARE(ui_img_lowfuel_png);    // assets/lowFuel.png
LV_IMG_DECLARE(ui_img_parking_brake_png);    // assets/parking_brake.png
LV_IMG_DECLARE(ui_img_cast_32__png);    // assets/cast_32 .png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_3103_png);    // assets/3103.png
LV_IMG_DECLARE(ui_img_slip_png);    // assets/Slip.png
LV_IMG_DECLARE(ui_img_drizzle_png);    // assets/drizzle.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_fog_png);    // assets/fog.png
LV_IMG_DECLARE(ui_img_storm_png);    // assets/storm.png
LV_IMG_DECLARE(ui_img_sunny_png);    // assets/sunny.png
LV_IMG_DECLARE(ui_img_windy_png);    // assets/windy.png
LV_IMG_DECLARE(ui_img_valet_off_png);    // assets/valet_OFF.png
LV_IMG_DECLARE(ui_img_valet_on_png);    // assets/valet_ON.png
LV_IMG_DECLARE(ui_img_button_png);    // assets/button.png
LV_IMG_DECLARE(ui_img_btn_1_inact_png);    // assets/btn_1_inact.png
LV_IMG_DECLARE(ui_img_btn_1_act_png);    // assets/btn_1_act.png
LV_IMG_DECLARE(ui_img_home_15493404_png);    // assets/home_15493404.png
LV_IMG_DECLARE(ui_img_btn_knob1_png);    // assets/btn_knob1.png
LV_IMG_DECLARE(ui_img_arrow_right_png);    // assets/arrow_right.png
LV_IMG_DECLARE(ui_img_arrow_left_png);    // assets/arrow_left.png
LV_IMG_DECLARE(ui_img_icn_play_png);    // assets/icn_play.png
LV_IMG_DECLARE(ui_img_radio_png);    // assets/Radio.png
LV_IMG_DECLARE(ui_img_reset_brightness_png);    // assets/reset_brightness.png
LV_IMG_DECLARE(ui_img_road_2_png);    // assets/road_2.png
LV_IMG_DECLARE(ui_img_diagnostic_png);    // assets/diagnostic.png

// FONTS
LV_FONT_DECLARE(ui_font_orbitron25);
LV_FONT_DECLARE(ui_font_orbitron40);
LV_FONT_DECLARE(ui_font_orbitron60);
LV_FONT_DECLARE(ui_font_Rubik130);
LV_FONT_DECLARE(ui_font_Rubik150);
LV_FONT_DECLARE(ui_font_Rubik37);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
