// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void updateSlot(lv_event_t * e)
{
	// Your code here
}

void updateSlot2(lv_event_t * e)
{
	// Your code here
}

void hide_chart_timer(lv_event_t * e)
{
	// Your code here
}

void saveBrightnessSetting(lv_event_t * e)
{
	// Your code here
}
