// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void updateSlot(lv_event_t * e);
void updateSlot2(lv_event_t * e);
void hide_chart_timer(lv_event_t * e);
void saveBrightnessSetting(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
