// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Dropdown6 = NULL;
lv_obj_t * ui_Slot6 = NULL;
lv_obj_t * ui_Dropdown7 = NULL;
lv_obj_t * ui_Slot7 = NULL;
lv_obj_t * ui_Dropdown8 = NULL;
lv_obj_t * ui_Slot8 = NULL;
lv_obj_t * ui_Dropdown9 = NULL;
lv_obj_t * ui_Slot9 = NULL;
lv_obj_t * ui_Dropdown10 = NULL;
lv_obj_t * ui_Slot10 = NULL;
lv_obj_t * ui_VSS1 = NULL;
lv_obj_t * ui_speedunit2 = NULL;
lv_obj_t * ui_Fuel1 = NULL;
lv_obj_t * ui_FUELBAR1 = NULL;
lv_obj_t * ui_FUEL1 = NULL;
lv_obj_t * ui_GEAR3 = NULL;
lv_obj_t * ui_Chart3 = NULL;
lv_obj_t * ui_Chart3_Xaxis = NULL;
lv_obj_t * ui_Chart3_Yaxis1 = NULL;
lv_obj_t * ui_Chart3_Yaxis2 = NULL;
lv_obj_t * ui_Button4 = NULL;
// event funtions
void ui_event_Dropdown6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot2(e);
    }
}

void ui_event_Dropdown7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot2(e);
    }
}

void ui_event_Dropdown8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot2(e);
    }
}

void ui_event_Dropdown9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot2(e);
    }
}

void ui_event_Dropdown10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot2(e);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
        hide_chart_timer(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Screen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Screen2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown6 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_dir(ui_Dropdown6, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown6, "Lambda A\nAfr Target\nAfr\nLambda Corr %\nTotal F Corr %\nBoost Tar");
    lv_obj_set_width(ui_Dropdown6, 174);
    lv_obj_set_height(ui_Dropdown6, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Dropdown6, -309);
    lv_obj_set_y(ui_Dropdown6, 156);
    lv_obj_set_align(ui_Dropdown6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown6, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown6, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown6, lv_color_hex(0x8E8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown6, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown6, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown6, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown6), lv_color_hex(0x030303),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown6), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown6), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown6), lv_color_hex(0xF35007),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown6), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown6), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown6), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown6), 75,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(lv_dropdown_get_list(ui_Dropdown6), true,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Slot6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot6, -324);
    lv_obj_set_y(ui_Slot6, 204);
    lv_obj_set_align(ui_Slot6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot6, "-");
    lv_obj_remove_flag(ui_Slot6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot6, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown7 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_dir(ui_Dropdown7, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown7,
                            "Oil Press kPa\nFuel Press kPa\nBoost kPa\nUser CH1\nUser CH2\nUser CH3\nUser CH4\nUser CH5\nUser CH6");
    lv_obj_set_width(ui_Dropdown7, 160);
    lv_obj_set_height(ui_Dropdown7, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Dropdown7, -140);
    lv_obj_set_y(ui_Dropdown7, 155);
    lv_obj_set_align(ui_Dropdown7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown7, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown7, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown7, lv_color_hex(0x8E8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown7, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown7, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown7, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown7), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown7), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown7), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown7), lv_color_hex(0xF35007),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown7), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown7), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown7), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Slot7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot7, -145);
    lv_obj_set_y(ui_Slot7, 204);
    lv_obj_set_align(ui_Slot7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot7, "-");
    lv_obj_remove_flag(ui_Slot7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot7, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown8 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_dir(ui_Dropdown8, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown8,
                            "ECU Logging\nError Codes\nFuel Tank\nUser CH7\nUser CH8\nUser CH9\nUser CH10\nUser CH11\nUser CH12");
    lv_obj_set_width(ui_Dropdown8, 146);
    lv_obj_set_height(ui_Dropdown8, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Dropdown8, 14);
    lv_obj_set_y(ui_Dropdown8, 156);
    lv_obj_set_align(ui_Dropdown8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown8, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown8, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown8, lv_color_hex(0x8E8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown8, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown8, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown8, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown8), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown8), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown8), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown8), lv_color_hex(0xF35007),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown8), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown8), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown8), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Slot8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot8, 12);
    lv_obj_set_y(ui_Slot8, 204);
    lv_obj_set_align(ui_Slot8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot8, "-");
    lv_obj_remove_flag(ui_Slot8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot8, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown9 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_dir(ui_Dropdown9, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown9, "Coolant °C\nIat Temp °C\nCPU Temp °C\nThrottle%\nBaro kPa");
    lv_obj_set_width(ui_Dropdown9, 148);
    lv_obj_set_height(ui_Dropdown9, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Dropdown9, 162);
    lv_obj_set_y(ui_Dropdown9, 156);
    lv_obj_set_align(ui_Dropdown9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown9, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown9, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown9, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown9, lv_color_hex(0x8E8B8B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown9, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown9, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown9, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown9), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown9), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown9), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown9), lv_color_hex(0xF3501E),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown9), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown9), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown9), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Slot9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot9, 161);
    lv_obj_set_y(ui_Slot9, 204);
    lv_obj_set_align(ui_Slot9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot9, "-");
    lv_obj_remove_flag(ui_Slot9, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot9, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown10 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_dir(ui_Dropdown10, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown10, "Battery V+\nRev Limiter\nBoost Duty %");
    lv_obj_set_width(ui_Dropdown10, 154);
    lv_obj_set_height(ui_Dropdown10, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Dropdown10, 315);
    lv_obj_set_y(ui_Dropdown10, 156);
    lv_obj_set_align(ui_Dropdown10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown10, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown10, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown10, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown10, lv_color_hex(0x4A4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown10, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown10, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown10), lv_color_hex(0x040404),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown10), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown10), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown10), lv_color_hex(0xF35007),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown10), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown10), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown10), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Slot10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot10, 317);
    lv_obj_set_y(ui_Slot10, 204);
    lv_obj_set_align(ui_Slot10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot10, "-");
    lv_obj_remove_flag(ui_Slot10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot10, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slot10, lv_color_hex(0x1CDB41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slot10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VSS1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_VSS1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VSS1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VSS1, 3);
    lv_obj_set_y(ui_VSS1, 28);
    lv_obj_set_align(ui_VSS1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VSS1, "0");
    lv_obj_set_style_text_font(ui_VSS1, &ui_font_Rubik130, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedunit2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_speedunit2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedunit2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedunit2, 227);
    lv_obj_set_y(ui_speedunit2, 65);
    lv_obj_set_align(ui_speedunit2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedunit2, "km/h");
    lv_obj_remove_flag(ui_speedunit2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_speedunit2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedunit2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedunit2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Fuel1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Fuel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Fuel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Fuel1, 85);
    lv_obj_set_y(ui_Fuel1, 105);
    lv_obj_set_align(ui_Fuel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Fuel1, "Fuel");
    lv_obj_remove_flag(ui_Fuel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Fuel1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUELBAR1 = lv_bar_create(ui_Screen2);
    lv_obj_set_width(ui_FUELBAR1, 202);
    lv_obj_set_height(ui_FUELBAR1, 2);
    lv_obj_set_x(ui_FUELBAR1, 162);
    lv_obj_set_y(ui_FUELBAR1, 119);
    lv_obj_set_align(ui_FUELBAR1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FUELBAR1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_FUELBAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUELBAR1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUELBAR1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FUELBAR1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUELBAR1, lv_color_hex(0xC4FF0E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUELBAR1, 205, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_FUELBAR1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_FUELBAR1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_FUELBAR1,
                                                                                               lv_obj_get_style_pad_right(ui_FUELBAR1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_FUEL1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_FUEL1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL1, 188);
    lv_obj_set_y(ui_FUEL1, 101);
    lv_obj_set_align(ui_FUEL1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FUEL1, "--");
    lv_obj_remove_flag(ui_FUEL1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_FUEL1, lv_color_hex(0xC4FF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FUEL1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FUEL1, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GEAR3 = lv_roller_create(ui_Screen2);
    lv_roller_set_options(ui_GEAR3, "N\n1\n2\n3\n4\n5\n", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_GEAR3, 118);
    lv_obj_set_width(ui_GEAR3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_GEAR3, -315);
    lv_obj_set_y(ui_GEAR3, 22);
    lv_obj_set_align(ui_GEAR3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GEAR3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_GEAR3, lv_color_hex(0xC4FF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR3, &ui_font_Rubik150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GEAR3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GEAR3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_GEAR3, lv_color_hex(0xC4FF0E), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR3, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR3, &ui_font_Rubik150, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR3, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR3, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Chart3 = lv_chart_create(ui_Screen2);
    lv_obj_set_width(ui_Chart3, 869);
    lv_obj_set_height(ui_Chart3, 223);
    lv_obj_set_x(ui_Chart3, 2);
    lv_obj_set_y(ui_Chart3, -163);
    lv_obj_set_align(ui_Chart3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Chart3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_add_flag(ui_Chart3, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_Chart3, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_Chart3, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_Chart3, 11);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_PRIMARY_Y, 50, 450);
    lv_chart_set_range(ui_Chart3, LV_CHART_AXIS_SECONDARY_Y, 50, 450);
    lv_chart_set_div_line_count(ui_Chart3, 5, 9);
    lv_obj_set_style_bg_color(ui_Chart3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_Chart3, lv_color_hex(0x6F6F72), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_Chart3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Chart3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Chart3_Xaxis = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_Chart3_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_Chart3_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Chart3_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_Chart3_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_Chart3_Xaxis, 8, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_Chart3_Xaxis, 0, 9 > 0 ? 9 - 1 : 0);
    lv_scale_set_total_tick_count(ui_Chart3_Xaxis, (9 > 0 ? 9 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Xaxis, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis1 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_Chart3_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_Chart3,
                                                                   LV_PART_MAIN) - lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart3_Yaxis1,  50, 450);
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_Chart3_Yaxis2 = lv_scale_create(ui_Chart3);
    lv_scale_set_mode(ui_Chart3_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_Chart3_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_Chart3_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_Chart3_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_Chart3,
                                                                   LV_PART_MAIN) + lv_obj_get_style_border_width(ui_Chart3, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_Chart3_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_Chart3_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_Chart3_Yaxis2,  50, 450);
    lv_scale_set_total_tick_count(ui_Chart3_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_Chart3_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_Chart3_series_1 = lv_chart_add_series(ui_Chart3, lv_color_hex(0x3850D6),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart3_series_1_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_1, ui_Chart3_series_1_array);
    lv_chart_series_t * ui_Chart3_series_2 = lv_chart_add_series(ui_Chart3, lv_color_hex(0xF60F0F),
                                                                 LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_Chart3_series_2_array[] = { 0 };
    lv_chart_set_ext_y_array(ui_Chart3, ui_Chart3_series_2, ui_Chart3_series_2_array);
    lv_obj_set_style_bg_color(ui_Chart3, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart3, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Chart3, lv_color_hex(0x3220C6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Chart3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_size(ui_Chart3, 1, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_Chart3, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_Chart3, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Button4 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button4, 310);
    lv_obj_set_height(ui_Button4, 166);
    lv_obj_set_x(ui_Button4, 0);
    lv_obj_set_y(ui_Button4, 35);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x2E3B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown6, ui_event_Dropdown6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown7, ui_event_Dropdown7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown8, ui_event_Dropdown8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown9, ui_event_Dropdown9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown10, ui_event_Dropdown10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Dropdown6 = NULL;
    ui_Slot6 = NULL;
    ui_Dropdown7 = NULL;
    ui_Slot7 = NULL;
    ui_Dropdown8 = NULL;
    ui_Slot8 = NULL;
    ui_Dropdown9 = NULL;
    ui_Slot9 = NULL;
    ui_Dropdown10 = NULL;
    ui_Slot10 = NULL;
    ui_VSS1 = NULL;
    ui_speedunit2 = NULL;
    ui_Fuel1 = NULL;
    ui_FUELBAR1 = NULL;
    ui_FUEL1 = NULL;
    ui_GEAR3 = NULL;
    ui_Chart3 = NULL;
    ui_Button4 = NULL;

}
