// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN6_H
#define UI_SCREEN6_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen6
extern void ui_Screen6_screen_init(void);
extern void ui_Screen6_screen_destroy(void);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_ControlPanel;
extern lv_obj_t * ui_BoostContainer;
extern lv_obj_t * ui_RowStreet;
extern lv_obj_t * ui_LightStreet;
extern lv_obj_t * ui_LabelStreet;
extern lv_obj_t * ui_BtnStreet;
extern lv_obj_t * ui_RowSport;
extern lv_obj_t * ui_LightSport;
extern lv_obj_t * ui_LabelSport;
extern lv_obj_t * ui_BtnSport;
extern lv_obj_t * ui_RowRace;
extern lv_obj_t * ui_LightRace;
extern lv_obj_t * ui_LabelRace;
extern lv_obj_t * ui_BtnRace;
extern lv_obj_t * ui_LabelBOOSTMODE;
extern lv_obj_t * ui_LabelCONTROLHUB;
extern lv_obj_t * ui_PanelTractionCntrl;
extern lv_obj_t * ui_LabelTC;
extern lv_obj_t * ui_SliderTraction;
extern lv_obj_t * ui_LabelTractionValue;
extern lv_obj_t * ui_ValetPanel;
extern lv_obj_t * ui_LabelTraction1;
extern lv_obj_t * ui_ValetSwitch;
extern lv_obj_t * ui_PanelScramble;
extern lv_obj_t * ui_BtnScramble;
extern lv_obj_t * ui_LabelScramble;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

