// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern void ui_event_BTNHome(lv_event_t * e);
extern lv_obj_t * ui_BTNHome;
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_btnDisplay;
extern lv_obj_t * ui_btnSpeedunit;
extern lv_obj_t * ui_btnDiagnostics;
extern lv_obj_t * ui_MenuContainer;
extern lv_obj_t * ui_brightnessContainer;
extern lv_obj_t * ui_Label100Brightness1;
extern lv_obj_t * ui_Label0Brightness1;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_LabelBrightness1;
extern lv_obj_t * ui_Slider1Value;
extern void ui_event_dimmerSaveBTN(lv_event_t * e);
extern lv_obj_t * ui_dimmerSaveBTN;
extern lv_obj_t * ui_SaveBrightness1;
extern lv_obj_t * ui_speedUnitContainer;
extern lv_obj_t * ui_KMHCheckbox;
extern lv_obj_t * ui_MPHCheckbox;
extern lv_obj_t * ui_LabelODO;
extern lv_obj_t * ui_ODOMETER;
extern lv_obj_t * ui_LabelSpeedUnits;
extern lv_obj_t * ui_diagnosticContainer;
extern lv_obj_t * ui_LabelDiagnostics;
extern lv_obj_t * ui_ErrorCodeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

