// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen8 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_ArcVolume = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_LabelStation = NULL;
lv_obj_t * ui_BtnNext = NULL;
lv_obj_t * ui_BtnPrev = NULL;
lv_obj_t * ui_BtnPlay = NULL;
lv_obj_t * ui_LabelTrack = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_ImageLogo = NULL;
lv_obj_t * ui_WaveVisualizer = NULL;
// event funtions
void ui_event_Screen8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen8_screen_init(void)
{
    ui_Screen8 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen8);
    lv_obj_set_width(ui_Panel5, 931);
    lv_obj_set_height(ui_Panel5, 244);
    lv_obj_set_x(ui_Panel5, -4);
    lv_obj_set_y(ui_Panel5, -26);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel5, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel5, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel5, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_Panel5);
    lv_image_set_src(ui_Image10, &ui_img_btn_knob1_png);
    lv_obj_set_width(ui_Image10, 115);
    lv_obj_set_height(ui_Image10, 120);
    lv_obj_set_x(ui_Image10, 51);
    lv_obj_set_y(ui_Image10, 6);
    lv_obj_set_align(ui_Image10, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_image_set_inner_align(ui_Image10, LV_IMAGE_ALIGN_TILE);

    ui_ArcVolume = lv_arc_create(ui_Panel5);
    lv_obj_set_width(ui_ArcVolume, 103);
    lv_obj_set_height(ui_ArcVolume, 110);
    lv_obj_set_x(ui_ArcVolume, 57);
    lv_obj_set_y(ui_ArcVolume, 6);
    lv_obj_set_align(ui_ArcVolume, LV_ALIGN_LEFT_MID);
    lv_arc_set_range(ui_ArcVolume, 0, 21);
    lv_arc_set_value(ui_ArcVolume, 15);
    lv_arc_set_bg_angles(ui_ArcVolume, 129, 51);
    lv_obj_set_style_pad_left(ui_ArcVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ArcVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ArcVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ArcVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcVolume, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcVolume, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcVolume, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcVolume, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcVolume, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcVolume, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcVolume, lv_color_hex(0x50FF7D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcVolume, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel4, 710);
    lv_obj_set_height(ui_Panel4, 229);
    lv_obj_set_x(ui_Panel4, 14);
    lv_obj_set_y(ui_Panel4, -1);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x0B40AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel4, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Panel4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStation = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelStation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStation, 110);
    lv_obj_set_y(ui_LabelStation, -36);
    lv_obj_set_align(ui_LabelStation, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStation, "\"No Internet\"");
    lv_obj_set_style_text_font(ui_LabelStation, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNext = lv_button_create(ui_Panel4);
    lv_obj_set_width(ui_BtnNext, 86);
    lv_obj_set_height(ui_BtnNext, 60);
    lv_obj_set_x(ui_BtnNext, 514);
    lv_obj_set_y(ui_BtnNext, 130);
    lv_obj_add_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnNext, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNext, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNext, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BtnNext, &ui_img_arrow_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNext, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnNext, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnNext, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnNext, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BtnPrev = lv_button_create(ui_Panel4);
    lv_obj_set_width(ui_BtnPrev, 87);
    lv_obj_set_height(ui_BtnPrev, 60);
    lv_obj_set_x(ui_BtnPrev, 210);
    lv_obj_set_y(ui_BtnPrev, 130);
    lv_obj_add_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnPrev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPrev, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrev, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BtnPrev, &ui_img_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPrev, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnPrev, 200, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnPrev, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnPrev, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BtnPlay = lv_button_create(ui_Panel4);
    lv_obj_set_width(ui_BtnPlay, 116);
    lv_obj_set_height(ui_BtnPlay, 70);
    lv_obj_set_x(ui_BtnPlay, 350);
    lv_obj_set_y(ui_BtnPlay, 124);
    lv_obj_add_flag(ui_BtnPlay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnPlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPlay, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPlay, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BtnPlay, &ui_img_icn_play_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPlay, lv_color_hex(0x50FF7D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnPlay, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnPlay, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnPlay, 5, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelTrack = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_LabelTrack, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTrack, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTrack, 76);
    lv_obj_set_y(ui_LabelTrack, 2);
    lv_obj_set_align(ui_LabelTrack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTrack, "\"WiFi not connected\"");
    lv_obj_set_style_text_color(ui_LabelTrack, lv_color_hex(0xBE1DBE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTrack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTrack, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_Panel4);
    lv_obj_set_width(ui_TextArea1, 245);
    lv_obj_set_height(ui_TextArea1, 42);
    lv_obj_set_x(ui_TextArea1, -213);
    lv_obj_set_y(ui_TextArea1, -71);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "INTERNET RADIO");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x0B40AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageLogo = lv_image_create(ui_Screen8);
    lv_image_set_src(ui_ImageLogo, &ui_img_radio_png);
    lv_obj_set_width(ui_ImageLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLogo, -139);
    lv_obj_set_y(ui_ImageLogo, 6);
    lv_obj_set_align(ui_ImageLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WaveVisualizer = lv_slider_create(ui_Screen8);
    lv_slider_set_value(ui_WaveVisualizer, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_WaveVisualizer) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_WaveVisualizer, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_WaveVisualizer, 368);
    lv_obj_set_height(ui_WaveVisualizer, 2);
    lv_obj_set_x(ui_WaveVisualizer, 174);
    lv_obj_set_y(ui_WaveVisualizer, -6);
    lv_obj_set_align(ui_WaveVisualizer, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_WaveVisualizer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaveVisualizer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WaveVisualizer, lv_color_hex(0xFF2424), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaveVisualizer, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WaveVisualizer, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WaveVisualizer, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WaveVisualizer, lv_color_hex(0xFF2424), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WaveVisualizer, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WaveVisualizer, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_WaveVisualizer, LV_BORDER_SIDE_FULL, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_WaveVisualizer, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_WaveVisualizer,
                                                                                                     lv_obj_get_style_pad_right(ui_WaveVisualizer, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_Screen8, ui_event_Screen8, LV_EVENT_ALL, NULL);

}

void ui_Screen8_screen_destroy(void)
{
    if(ui_Screen8) lv_obj_del(ui_Screen8);

    // NULL screen variables
    ui_Screen8 = NULL;
    ui_Panel5 = NULL;
    ui_Image10 = NULL;
    ui_ArcVolume = NULL;
    ui_Panel4 = NULL;
    ui_LabelStation = NULL;
    ui_BtnNext = NULL;
    ui_BtnPrev = NULL;
    ui_BtnPlay = NULL;
    ui_LabelTrack = NULL;
    ui_TextArea1 = NULL;
    ui_ImageLogo = NULL;
    ui_WaveVisualizer = NULL;

}
