// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen7 = NULL;
lv_obj_t * ui_BTNHome2 = NULL;
lv_obj_t * ui_HOME2 = NULL;
// event funtions
void ui_event_BTNHome2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen7_screen_init(void)
{
    ui_Screen7 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen7, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNHome2 = lv_imagebutton_create(ui_Screen7);
    lv_imagebutton_set_src(ui_BTNHome2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imagebutton_set_src(ui_BTNHome2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_obj_set_height(ui_BTNHome2, 56);
    lv_obj_set_width(ui_BTNHome2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BTNHome2, -5);
    lv_obj_set_y(ui_BTNHome2, -204);
    lv_obj_set_align(ui_BTNHome2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_image_src(ui_BTNHome2, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME2 = lv_image_create(ui_BTNHome2);
    lv_image_set_src(ui_HOME2, &ui_img_home_15493404_png);
    lv_obj_set_width(ui_HOME2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_HOME2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_HOME2, -1);
    lv_obj_set_y(ui_HOME2, 1);
    lv_obj_set_align(ui_HOME2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HOME2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BTNHome2, ui_event_BTNHome2, LV_EVENT_ALL, NULL);

}

void ui_Screen7_screen_destroy(void)
{
    if(ui_Screen7) lv_obj_del(ui_Screen7);

    // NULL screen variables
    ui_Screen7 = NULL;
    ui_BTNHome2 = NULL;
    ui_HOME2 = NULL;

}
