// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN8_H
#define UI_SCREEN8_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen8
extern void ui_Screen8_screen_init(void);
extern void ui_Screen8_screen_destroy(void);
extern void ui_event_Screen8(lv_event_t * e);
extern lv_obj_t * ui_Screen8;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_ArcVolume;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabelStation;
extern lv_obj_t * ui_BtnNext;
extern lv_obj_t * ui_BtnPrev;
extern lv_obj_t * ui_BtnPlay;
extern lv_obj_t * ui_LabelTrack;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_ImageLogo;
extern lv_obj_t * ui_WaveVisualizer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

