// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_BTNHome = NULL;
lv_obj_t * ui_HOME = NULL;
lv_obj_t * ui_btnDisplay = NULL;
lv_obj_t * ui_btnSpeedunit = NULL;
lv_obj_t * ui_btnDiagnostics = NULL;
lv_obj_t * ui_MenuContainer = NULL;
lv_obj_t * ui_brightnessContainer = NULL;
lv_obj_t * ui_Label100Brightness1 = NULL;
lv_obj_t * ui_Label0Brightness1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_LabelBrightness1 = NULL;
lv_obj_t * ui_Slider1Value = NULL;
lv_obj_t * ui_dimmerSaveBTN = NULL;
lv_obj_t * ui_SaveBrightness1 = NULL;
lv_obj_t * ui_speedUnitContainer = NULL;
lv_obj_t * ui_KMHCheckbox = NULL;
lv_obj_t * ui_MPHCheckbox = NULL;
lv_obj_t * ui_LabelODO = NULL;
lv_obj_t * ui_ODOMETER = NULL;
lv_obj_t * ui_LabelSpeedUnits = NULL;
lv_obj_t * ui_diagnosticContainer = NULL;
lv_obj_t * ui_LabelDiagnostics = NULL;
lv_obj_t * ui_ErrorCodeLabel = NULL;
// event funtions
void ui_event_BTNHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_dimmerSaveBTN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        saveBrightnessSetting(e);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x050500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNHome = lv_imagebutton_create(ui_Screen5);
    lv_imagebutton_set_src(ui_BTNHome, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imagebutton_set_src(ui_BTNHome, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_obj_set_height(ui_BTNHome, 56);
    lv_obj_set_width(ui_BTNHome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_BTNHome, 349);
    lv_obj_set_y(ui_BTNHome, -162);
    lv_obj_set_align(ui_BTNHome, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_image_src(ui_BTNHome, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HOME = lv_image_create(ui_BTNHome);
    lv_image_set_src(ui_HOME, &ui_img_home_15493404_png);
    lv_obj_set_width(ui_HOME, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_HOME, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_HOME, -1);
    lv_obj_set_y(ui_HOME, 1);
    lv_obj_set_align(ui_HOME, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HOME, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnDisplay = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_btnDisplay, 63);
    lv_obj_set_height(ui_btnDisplay, 55);
    lv_obj_set_x(ui_btnDisplay, -358);
    lv_obj_set_y(ui_btnDisplay, -179);
    lv_obj_set_align(ui_btnDisplay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDisplay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnDisplay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnDisplay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnDisplay, &ui_img_reset_brightness_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSpeedunit = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_btnSpeedunit, 69);
    lv_obj_set_height(ui_btnSpeedunit, 60);
    lv_obj_set_x(ui_btnSpeedunit, -349);
    lv_obj_set_y(ui_btnSpeedunit, -86);
    lv_obj_set_align(ui_btnSpeedunit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSpeedunit, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSpeedunit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSpeedunit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSpeedunit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnSpeedunit, &ui_img_road_2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnDiagnostics = lv_button_create(ui_Screen5);
    lv_obj_set_width(ui_btnDiagnostics, 76);
    lv_obj_set_height(ui_btnDiagnostics, 60);
    lv_obj_set_x(ui_btnDiagnostics, -352);
    lv_obj_set_y(ui_btnDiagnostics, 13);
    lv_obj_set_align(ui_btnDiagnostics, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnDiagnostics, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnDiagnostics, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnDiagnostics, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDiagnostics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnDiagnostics, &ui_img_diagnostic_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuContainer = lv_obj_create(ui_Screen5);
    lv_obj_remove_style_all(ui_MenuContainer);
    lv_obj_set_width(ui_MenuContainer, 507);
    lv_obj_set_height(ui_MenuContainer, 363);
    lv_obj_set_x(ui_MenuContainer, 137);
    lv_obj_set_y(ui_MenuContainer, 47);
    lv_obj_set_align(ui_MenuContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MenuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brightnessContainer = lv_obj_create(ui_MenuContainer);
    lv_obj_remove_style_all(ui_brightnessContainer);
    lv_obj_set_width(ui_brightnessContainer, 496);
    lv_obj_set_height(ui_brightnessContainer, 363);
    lv_obj_set_x(ui_brightnessContainer, -4);
    lv_obj_set_y(ui_brightnessContainer, 1);
    lv_obj_set_align(ui_brightnessContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brightnessContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_brightnessContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_brightnessContainer, lv_color_hex(0x494848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_brightnessContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brightnessContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label100Brightness1 = lv_label_create(ui_brightnessContainer);
    lv_obj_set_width(ui_Label100Brightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label100Brightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label100Brightness1, 145);
    lv_obj_set_y(ui_Label100Brightness1, 5);
    lv_obj_set_align(ui_Label100Brightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label100Brightness1, "100");
    lv_obj_set_style_text_font(ui_Label100Brightness1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label0Brightness1 = lv_label_create(ui_brightnessContainer);
    lv_obj_set_width(ui_Label0Brightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label0Brightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label0Brightness1, -137);
    lv_obj_set_y(ui_Label0Brightness1, 6);
    lv_obj_set_align(ui_Label0Brightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label0Brightness1, "0");
    lv_obj_set_style_text_font(ui_Label0Brightness1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_brightnessContainer);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 252);
    lv_obj_set_height(ui_Slider1, 2);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, 7);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xCDCACA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xF90707), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_Slider1, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xDFDCDC), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Slider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Slider1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Slider1, 13, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Slider1, 13, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelBrightness1 = lv_label_create(ui_brightnessContainer);
    lv_obj_set_width(ui_LabelBrightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightness1, -10);
    lv_obj_set_y(ui_LabelBrightness1, -146);
    lv_obj_set_align(ui_LabelBrightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBrightness1, "Brightness level");
    lv_obj_set_style_text_color(ui_LabelBrightness1, lv_color_hex(0x929090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightness1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightness1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1Value = lv_label_create(ui_brightnessContainer);
    lv_obj_set_width(ui_Slider1Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slider1Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slider1Value, -126);
    lv_obj_set_y(ui_Slider1Value, -22);
    lv_obj_set_align(ui_Slider1Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slider1Value, "0");
    lv_obj_set_style_text_font(ui_Slider1Value, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dimmerSaveBTN = lv_imagebutton_create(ui_brightnessContainer);
    lv_imagebutton_set_src(ui_dimmerSaveBTN, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_btn_1_inact_png, NULL);
    lv_imagebutton_set_src(ui_dimmerSaveBTN, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_btn_1_act_png, NULL);
    lv_obj_set_height(ui_dimmerSaveBTN, 56);
    lv_obj_set_width(ui_dimmerSaveBTN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_dimmerSaveBTN, 2);
    lv_obj_set_y(ui_dimmerSaveBTN, 91);
    lv_obj_set_align(ui_dimmerSaveBTN, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_image_src(ui_dimmerSaveBTN, &ui_img_btn_1_act_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveBrightness1 = lv_label_create(ui_dimmerSaveBTN);
    lv_obj_set_width(ui_SaveBrightness1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveBrightness1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveBrightness1, 0);
    lv_obj_set_y(ui_SaveBrightness1, 1);
    lv_obj_set_align(ui_SaveBrightness1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveBrightness1, "Save");
    lv_obj_set_style_text_color(ui_SaveBrightness1, lv_color_hex(0x060000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveBrightness1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SaveBrightness1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedUnitContainer = lv_obj_create(ui_MenuContainer);
    lv_obj_remove_style_all(ui_speedUnitContainer);
    lv_obj_set_width(ui_speedUnitContainer, 496);
    lv_obj_set_height(ui_speedUnitContainer, 363);
    lv_obj_set_x(ui_speedUnitContainer, -4);
    lv_obj_set_y(ui_speedUnitContainer, 0);
    lv_obj_set_align(ui_speedUnitContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_speedUnitContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_speedUnitContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_speedUnitContainer, lv_color_hex(0x494848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_speedUnitContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_speedUnitContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KMHCheckbox = lv_checkbox_create(ui_speedUnitContainer);
    lv_checkbox_set_text(ui_KMHCheckbox, "KM/h");
    lv_obj_set_width(ui_KMHCheckbox, 78);
    lv_obj_set_height(ui_KMHCheckbox, 22);
    lv_obj_set_x(ui_KMHCheckbox, -115);
    lv_obj_set_y(ui_KMHCheckbox, -75);
    lv_obj_set_align(ui_KMHCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_KMHCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_MPHCheckbox = lv_checkbox_create(ui_speedUnitContainer);
    lv_checkbox_set_text(ui_MPHCheckbox, "MPH");
    lv_obj_set_width(ui_MPHCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPHCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPHCheckbox, 132);
    lv_obj_set_y(ui_MPHCheckbox, -74);
    lv_obj_set_align(ui_MPHCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPHCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelODO = lv_label_create(ui_speedUnitContainer);
    lv_obj_set_width(ui_LabelODO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelODO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelODO, -144);
    lv_obj_set_y(ui_LabelODO, 43);
    lv_obj_set_align(ui_LabelODO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelODO, "Odometer:");
    lv_obj_set_style_text_color(ui_LabelODO, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelODO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelODO, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ODOMETER = lv_label_create(ui_speedUnitContainer);
    lv_obj_set_width(ui_ODOMETER, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ODOMETER, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ODOMETER, 4);
    lv_obj_set_y(ui_ODOMETER, 44);
    lv_obj_set_align(ui_ODOMETER, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ODOMETER, "- - -");
    lv_obj_set_style_text_font(ui_ODOMETER, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSpeedUnits = lv_label_create(ui_speedUnitContainer);
    lv_obj_set_width(ui_LabelSpeedUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSpeedUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSpeedUnits, -18);
    lv_obj_set_y(ui_LabelSpeedUnits, -147);
    lv_obj_set_align(ui_LabelSpeedUnits, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSpeedUnits, "SPEED Units");
    lv_obj_set_style_text_color(ui_LabelSpeedUnits, lv_color_hex(0xC5C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSpeedUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSpeedUnits, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_diagnosticContainer = lv_obj_create(ui_MenuContainer);
    lv_obj_remove_style_all(ui_diagnosticContainer);
    lv_obj_set_width(ui_diagnosticContainer, 496);
    lv_obj_set_height(ui_diagnosticContainer, 363);
    lv_obj_set_x(ui_diagnosticContainer, -4);
    lv_obj_set_y(ui_diagnosticContainer, 0);
    lv_obj_set_align(ui_diagnosticContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_diagnosticContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_diagnosticContainer, lv_color_hex(0x494848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_diagnosticContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_diagnosticContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDiagnostics = lv_label_create(ui_diagnosticContainer);
    lv_obj_set_width(ui_LabelDiagnostics, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDiagnostics, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDiagnostics, -17);
    lv_obj_set_y(ui_LabelDiagnostics, -147);
    lv_obj_set_align(ui_LabelDiagnostics, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDiagnostics, "DIAGNOSTICS");
    lv_obj_set_style_text_color(ui_LabelDiagnostics, lv_color_hex(0xC5C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDiagnostics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDiagnostics, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ErrorCodeLabel = lv_label_create(ui_diagnosticContainer);
    lv_obj_set_width(ui_ErrorCodeLabel, 338);
    lv_obj_set_height(ui_ErrorCodeLabel, 207);
    lv_obj_set_x(ui_ErrorCodeLabel, 11);
    lv_obj_set_y(ui_ErrorCodeLabel, 64);
    lv_obj_set_align(ui_ErrorCodeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ErrorCodeLabel, "\n");
    lv_obj_set_style_text_color(ui_ErrorCodeLabel, lv_color_hex(0xFB082C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ErrorCodeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ErrorCodeLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ErrorCodeLabel, lv_color_hex(0xDFD9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ErrorCodeLabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTNHome, ui_event_BTNHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dimmerSaveBTN, ui_event_dimmerSaveBTN, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_BTNHome = NULL;
    ui_HOME = NULL;
    ui_btnDisplay = NULL;
    ui_btnSpeedunit = NULL;
    ui_btnDiagnostics = NULL;
    ui_MenuContainer = NULL;
    ui_brightnessContainer = NULL;
    ui_Label100Brightness1 = NULL;
    ui_Label0Brightness1 = NULL;
    ui_Slider1 = NULL;
    ui_LabelBrightness1 = NULL;
    ui_Slider1Value = NULL;
    ui_dimmerSaveBTN = NULL;
    ui_SaveBrightness1 = NULL;
    ui_speedUnitContainer = NULL;
    ui_KMHCheckbox = NULL;
    ui_MPHCheckbox = NULL;
    ui_LabelODO = NULL;
    ui_ODOMETER = NULL;
    ui_LabelSpeedUnits = NULL;
    ui_diagnosticContainer = NULL;
    ui_LabelDiagnostics = NULL;
    ui_ErrorCodeLabel = NULL;

}
