// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern void ui_event_Dropdown1(lv_event_t * e);
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_Slot1;
extern void ui_event_Dropdown2(lv_event_t * e);
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Slot2;
extern void ui_event_Dropdown3(lv_event_t * e);
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Slot3;
extern void ui_event_Dropdown4(lv_event_t * e);
extern lv_obj_t * ui_Dropdown4;
extern lv_obj_t * ui_Slot4;
extern void ui_event_Dropdown5(lv_event_t * e);
extern lv_obj_t * ui_Dropdown5;
extern lv_obj_t * ui_Slot5;
extern lv_obj_t * ui_rpm1k;
extern lv_obj_t * ui_rpm2k;
extern lv_obj_t * ui_rpm3k;
extern lv_obj_t * ui_rpm4k;
extern lv_obj_t * ui_rpm5k;
extern lv_obj_t * ui_rpm6k;
extern lv_obj_t * ui_rpm7k;
extern lv_obj_t * ui_rpm8k;
extern lv_obj_t * ui_RPMBAR1;
extern lv_obj_t * ui_VSS;
extern lv_obj_t * ui_speedunit1;
extern lv_obj_t * ui_GEAR1;
extern lv_obj_t * ui_GEAR2;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_LTURN;
extern lv_obj_t * ui_RTURN;
extern lv_obj_t * ui_LOWFUEL;
extern lv_obj_t * ui_PARKING;
extern lv_obj_t * ui_CASTWIFI;
extern lv_obj_t * ui_StreetName;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_weatherLabel;
extern lv_obj_t * ui_weatherImage;
extern lv_obj_t * ui_LabelMaxSpeedLimit;
extern lv_obj_t * ui_LOWOIL;
extern lv_obj_t * ui_FUELBAR3;
extern lv_obj_t * ui_FUEL;
extern lv_obj_t * ui_FuelLevelLabel;
extern lv_obj_t * ui_MainAlertPanel;
extern lv_obj_t * ui_MainAlertText;
extern lv_obj_t * ui_PanelLaunch;
extern lv_obj_t * ui_LabelLaunchReady;
extern lv_obj_t * ui_LabelLaunchBoost;
extern lv_obj_t * ui_LabelLaunchTitle;
extern lv_obj_t * ui_Slip;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

