// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image14 = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image1, &ui_img_drizzle_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image3 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image3, &ui_img_rain_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image3, -90);
    lv_obj_set_y(ui_Image3, 3);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image4 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image4, &ui_img_fog_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image4, -164);
    lv_obj_set_y(ui_Image4, 2);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image6 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image6, &ui_img_storm_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image6, -237);
    lv_obj_set_y(ui_Image6, 4);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image7 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image7, &ui_img_sunny_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image7, 89);
    lv_obj_set_y(ui_Image7, 4);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Image14 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_Image14, &ui_img_windy_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_Image14, -312);
    lv_obj_set_y(ui_Image14, 3);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image1 = NULL;
    ui_Image3 = NULL;
    ui_Image4 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Image14 = NULL;

}
