// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label60ft;
extern lv_obj_t * ui_Label60ftRun1;
extern lv_obj_t * ui_Label01kph;
extern lv_obj_t * ui_LabelZeroToOnehundredRun1;
extern lv_obj_t * ui_Label14mile;
extern lv_obj_t * ui_LabelQuarterMileRun1;
extern lv_obj_t * ui_LabelmaxSpeed;
extern lv_obj_t * ui_LabelMaxSpeedRun1;
extern lv_obj_t * ui_Label60ft2;
extern lv_obj_t * ui_Label60ft4;
extern lv_obj_t * ui_speedunit3;
extern lv_obj_t * ui_speedunit8;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

