// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label60ft = NULL;
lv_obj_t * ui_Label60ftRun1 = NULL;
lv_obj_t * ui_Label01kph = NULL;
lv_obj_t * ui_LabelZeroToOnehundredRun1 = NULL;
lv_obj_t * ui_Label14mile = NULL;
lv_obj_t * ui_LabelQuarterMileRun1 = NULL;
lv_obj_t * ui_LabelmaxSpeed = NULL;
lv_obj_t * ui_LabelMaxSpeedRun1 = NULL;
lv_obj_t * ui_Label60ft2 = NULL;
lv_obj_t * ui_Label60ft4 = NULL;
lv_obj_t * ui_speedunit3 = NULL;
lv_obj_t * ui_speedunit8 = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen7, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen7_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x050505), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 390);
    lv_obj_set_height(ui_Panel1, 455);
    lv_obj_set_x(ui_Panel1, -9);
    lv_obj_set_y(ui_Panel1, 3);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 240, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60ft = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label60ft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60ft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60ft, -36);
    lv_obj_set_y(ui_Label60ft, -100);
    lv_obj_set_align(ui_Label60ft, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60ft, "60 ft:");
    lv_obj_remove_flag(ui_Label60ft, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label60ft, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60ft, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60ft, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60ftRun1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label60ftRun1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60ftRun1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60ftRun1, 109);
    lv_obj_set_y(ui_Label60ftRun1, -100);
    lv_obj_set_align(ui_Label60ftRun1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60ftRun1, "---");
    lv_obj_add_flag(ui_Label60ftRun1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Label60ftRun1,
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label60ftRun1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60ftRun1, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60ftRun1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label01kph = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label01kph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label01kph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label01kph, -82);
    lv_obj_set_y(ui_Label01kph, -21);
    lv_obj_set_align(ui_Label01kph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label01kph, "0-100: ");
    lv_obj_remove_flag(ui_Label01kph, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label01kph, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label01kph, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label01kph, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelZeroToOnehundredRun1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelZeroToOnehundredRun1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelZeroToOnehundredRun1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelZeroToOnehundredRun1, 111);
    lv_obj_set_y(ui_LabelZeroToOnehundredRun1, -22);
    lv_obj_set_align(ui_LabelZeroToOnehundredRun1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelZeroToOnehundredRun1, "---");
    lv_obj_remove_flag(ui_LabelZeroToOnehundredRun1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelZeroToOnehundredRun1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelZeroToOnehundredRun1, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelZeroToOnehundredRun1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14mile = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label14mile, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14mile, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14mile, -51);
    lv_obj_set_y(ui_Label14mile, 61);
    lv_obj_set_align(ui_Label14mile, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14mile, "1/4 mile:");
    lv_obj_remove_flag(ui_Label14mile, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label14mile, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14mile, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14mile, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelQuarterMileRun1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelQuarterMileRun1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelQuarterMileRun1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelQuarterMileRun1, 111);
    lv_obj_set_y(ui_LabelQuarterMileRun1, 79);
    lv_obj_set_align(ui_LabelQuarterMileRun1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelQuarterMileRun1, "---");
    lv_obj_remove_flag(ui_LabelQuarterMileRun1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelQuarterMileRun1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelQuarterMileRun1, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelQuarterMileRun1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelmaxSpeed = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelmaxSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelmaxSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelmaxSpeed, -68);
    lv_obj_set_y(ui_LabelmaxSpeed, 143);
    lv_obj_set_align(ui_LabelmaxSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelmaxSpeed, "Max:");
    lv_obj_remove_flag(ui_LabelmaxSpeed,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelmaxSpeed, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelmaxSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelmaxSpeed, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMaxSpeedRun1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_LabelMaxSpeedRun1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaxSpeedRun1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaxSpeedRun1, 4);
    lv_obj_set_y(ui_LabelMaxSpeedRun1, 181);
    lv_obj_set_align(ui_LabelMaxSpeedRun1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaxSpeedRun1, "---");
    lv_obj_remove_flag(ui_LabelMaxSpeedRun1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelMaxSpeedRun1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaxSpeedRun1, 225, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaxSpeedRun1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60ft2 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label60ft2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60ft2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60ft2, -13);
    lv_obj_set_y(ui_Label60ft2, -198);
    lv_obj_set_align(ui_Label60ft2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60ft2, "Run 1");
    lv_obj_remove_flag(ui_Label60ft2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label60ft2, lv_color_hex(0xED1B1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60ft2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60ft2, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label60ft4 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label60ft4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label60ft4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label60ft4, -1);
    lv_obj_set_y(ui_Label60ft4, 90);
    lv_obj_set_align(ui_Label60ft4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label60ft4, "___________________________________");
    lv_obj_set_style_text_color(ui_Label60ft4, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label60ft4, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label60ft4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedunit3 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_speedunit3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedunit3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedunit3, 104);
    lv_obj_set_y(ui_speedunit3, 179);
    lv_obj_set_align(ui_speedunit3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedunit3, "---");
    lv_obj_remove_flag(ui_speedunit3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_speedunit3, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedunit3, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedunit3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedunit8 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_speedunit8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedunit8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedunit8, -11);
    lv_obj_set_y(ui_speedunit8, -20);
    lv_obj_set_align(ui_speedunit8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedunit8, "---");
    lv_obj_remove_flag(ui_speedunit8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_speedunit8, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedunit8, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedunit8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 310);
    lv_obj_set_height(ui_Button3, 166);
    lv_obj_set_x(ui_Button3, 0);
    lv_obj_set_y(ui_Button3, -6);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x2E3B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel1 = NULL;
    ui_Label60ft = NULL;
    ui_Label60ftRun1 = NULL;
    ui_Label01kph = NULL;
    ui_LabelZeroToOnehundredRun1 = NULL;
    ui_Label14mile = NULL;
    ui_LabelQuarterMileRun1 = NULL;
    ui_LabelmaxSpeed = NULL;
    ui_LabelMaxSpeedRun1 = NULL;
    ui_Label60ft2 = NULL;
    ui_Label60ft4 = NULL;
    ui_speedunit3 = NULL;
    ui_speedunit8 = NULL;
    ui_Button3 = NULL;

}
