// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen6 = NULL;
lv_obj_t * ui_ControlPanel = NULL;
lv_obj_t * ui_BoostContainer = NULL;
lv_obj_t * ui_RowStreet = NULL;
lv_obj_t * ui_LightStreet = NULL;
lv_obj_t * ui_LabelStreet = NULL;
lv_obj_t * ui_BtnStreet = NULL;
lv_obj_t * ui_RowSport = NULL;
lv_obj_t * ui_LightSport = NULL;
lv_obj_t * ui_LabelSport = NULL;
lv_obj_t * ui_BtnSport = NULL;
lv_obj_t * ui_RowRace = NULL;
lv_obj_t * ui_LightRace = NULL;
lv_obj_t * ui_LabelRace = NULL;
lv_obj_t * ui_BtnRace = NULL;
lv_obj_t * ui_LabelBOOSTMODE = NULL;
lv_obj_t * ui_LabelCONTROLHUB = NULL;
lv_obj_t * ui_PanelTractionCntrl = NULL;
lv_obj_t * ui_LabelTC = NULL;
lv_obj_t * ui_SliderTraction = NULL;
lv_obj_t * ui_LabelTractionValue = NULL;
lv_obj_t * ui_ValetPanel = NULL;
lv_obj_t * ui_LabelTraction1 = NULL;
lv_obj_t * ui_ValetSwitch = NULL;
lv_obj_t * ui_PanelScramble = NULL;
lv_obj_t * ui_BtnScramble = NULL;
lv_obj_t * ui_LabelScramble = NULL;
lv_obj_t * ui_Button5 = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x050500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlPanel = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_ControlPanel, 908);
    lv_obj_set_height(ui_ControlPanel, 525);
    lv_obj_set_x(ui_ControlPanel, 6);
    lv_obj_set_y(ui_ControlPanel, -1);
    lv_obj_set_align(ui_ControlPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ControlPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ControlPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ControlPanel, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ControlPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ControlPanel, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ControlPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ControlPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ControlPanel, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_ControlPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_ControlPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ControlPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ControlPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BoostContainer = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_BoostContainer, 302);
    lv_obj_set_height(ui_BoostContainer, 230);
    lv_obj_set_x(ui_BoostContainer, 7);
    lv_obj_set_y(ui_BoostContainer, 15);
    lv_obj_remove_flag(ui_BoostContainer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BoostContainer, lv_color_hex(0x496F8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BoostContainer, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RowStreet = lv_obj_create(ui_BoostContainer);
    lv_obj_set_width(ui_RowStreet, 210);
    lv_obj_set_height(ui_RowStreet, 50);
    lv_obj_set_x(ui_RowStreet, 10);
    lv_obj_set_y(ui_RowStreet, 23);
    lv_obj_remove_flag(ui_RowStreet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RowStreet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RowStreet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightStreet = lv_obj_create(ui_RowStreet);
    lv_obj_set_width(ui_LightStreet, 12);
    lv_obj_set_height(ui_LightStreet, 30);
    lv_obj_set_x(ui_LightStreet, -12);
    lv_obj_set_y(ui_LightStreet, 0);
    lv_obj_set_align(ui_LightStreet, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_LightStreet, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_LightStreet, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightStreet, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightStreet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStreet = lv_label_create(ui_RowStreet);
    lv_obj_set_width(ui_LabelStreet, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStreet, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStreet, 23);
    lv_obj_set_y(ui_LabelStreet, 0);
    lv_obj_set_align(ui_LabelStreet, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelStreet, "STREET");
    lv_obj_remove_flag(ui_LabelStreet, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelStreet, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStreet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStreet, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStreet = lv_button_create(ui_RowStreet);
    lv_obj_set_width(ui_BtnStreet, 223);
    lv_obj_set_height(ui_BtnStreet, 50);
    lv_obj_set_x(ui_BtnStreet, 2);
    lv_obj_set_y(ui_BtnStreet, 0);
    lv_obj_set_align(ui_BtnStreet, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStreet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnStreet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnStreet, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStreet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RowSport = lv_obj_create(ui_BoostContainer);
    lv_obj_set_width(ui_RowSport, 209);
    lv_obj_set_height(ui_RowSport, 50);
    lv_obj_set_x(ui_RowSport, 10);
    lv_obj_set_y(ui_RowSport, 84);
    lv_obj_remove_flag(ui_RowSport, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RowSport, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RowSport, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightSport = lv_obj_create(ui_RowSport);
    lv_obj_set_width(ui_LightSport, 12);
    lv_obj_set_height(ui_LightSport, 30);
    lv_obj_set_x(ui_LightSport, -12);
    lv_obj_set_y(ui_LightSport, 0);
    lv_obj_set_align(ui_LightSport, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_LightSport, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_LightSport, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightSport, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightSport, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSport = lv_label_create(ui_RowSport);
    lv_obj_set_width(ui_LabelSport, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSport, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSport, 22);
    lv_obj_set_y(ui_LabelSport, 1);
    lv_obj_set_align(ui_LabelSport, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelSport, "SPORT");
    lv_obj_remove_flag(ui_LabelSport, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelSport, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSport, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSport, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSport = lv_button_create(ui_RowSport);
    lv_obj_set_width(ui_BtnSport, 223);
    lv_obj_set_height(ui_BtnSport, 50);
    lv_obj_set_x(ui_BtnSport, -1);
    lv_obj_set_y(ui_BtnSport, 0);
    lv_obj_set_align(ui_BtnSport, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnSport, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnSport, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnSport, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnSport, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RowRace = lv_obj_create(ui_BoostContainer);
    lv_obj_set_width(ui_RowRace, 208);
    lv_obj_set_height(ui_RowRace, 50);
    lv_obj_set_x(ui_RowRace, 10);
    lv_obj_set_y(ui_RowRace, 146);
    lv_obj_remove_flag(ui_RowRace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RowRace, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RowRace, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightRace = lv_obj_create(ui_RowRace);
    lv_obj_set_width(ui_LightRace, 12);
    lv_obj_set_height(ui_LightRace, 30);
    lv_obj_set_x(ui_LightRace, -12);
    lv_obj_set_y(ui_LightRace, 0);
    lv_obj_set_align(ui_LightRace, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_LightRace, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_LightRace, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightRace, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightRace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRace = lv_label_create(ui_RowRace);
    lv_obj_set_width(ui_LabelRace, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRace, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelRace, 23);
    lv_obj_set_y(ui_LabelRace, 1);
    lv_obj_set_align(ui_LabelRace, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelRace, "RACE");
    lv_obj_remove_flag(ui_LabelRace, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelRace, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRace, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRace, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnRace = lv_button_create(ui_RowRace);
    lv_obj_set_width(ui_BtnRace, 209);
    lv_obj_set_height(ui_BtnRace, 50);
    lv_obj_set_x(ui_BtnRace, -24);
    lv_obj_set_y(ui_BtnRace, -22);
    lv_obj_add_flag(ui_BtnRace, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BtnRace, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BtnRace, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnRace, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBOOSTMODE = lv_label_create(ui_BoostContainer);
    lv_obj_set_width(ui_LabelBOOSTMODE, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBOOSTMODE, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBOOSTMODE, -5);
    lv_obj_set_y(ui_LabelBOOSTMODE, -90);
    lv_obj_set_align(ui_LabelBOOSTMODE, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBOOSTMODE, "Boost Mode");
    lv_obj_remove_flag(ui_LabelBOOSTMODE,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelBOOSTMODE, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCONTROLHUB = lv_textarea_create(ui_ControlPanel);
    lv_obj_set_width(ui_LabelCONTROLHUB, 400);
    lv_obj_set_height(ui_LabelCONTROLHUB, 70);
    lv_obj_set_x(ui_LabelCONTROLHUB, 134);
    lv_obj_set_y(ui_LabelCONTROLHUB, -211);
    lv_obj_set_align(ui_LabelCONTROLHUB, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_LabelCONTROLHUB, "CONTROL HUB");
    lv_textarea_set_placeholder_text(ui_LabelCONTROLHUB, "Placeholder...");
    lv_obj_set_style_text_color(ui_LabelCONTROLHUB, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCONTROLHUB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCONTROLHUB, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelCONTROLHUB, lv_color_hex(0x2D2FD4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelCONTROLHUB, 80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTractionCntrl = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_PanelTractionCntrl, 515);
    lv_obj_set_height(ui_PanelTractionCntrl, 175);
    lv_obj_set_x(ui_PanelTractionCntrl, -25);
    lv_obj_set_y(ui_PanelTractionCntrl, 70);
    lv_obj_set_align(ui_PanelTractionCntrl, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_PanelTractionCntrl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTractionCntrl, lv_color_hex(0x496F8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTractionCntrl, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTC = lv_label_create(ui_PanelTractionCntrl);
    lv_obj_set_width(ui_LabelTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTC, -11);
    lv_obj_set_y(ui_LabelTC, 61);
    lv_obj_set_align(ui_LabelTC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTC, "Traction CTRL");
    lv_obj_remove_flag(ui_LabelTC, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelTC, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SliderTraction = lv_slider_create(ui_PanelTractionCntrl);
    lv_slider_set_value(ui_SliderTraction, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderTraction) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderTraction, 0,
                                                                                                   LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderTraction, 378);
    lv_obj_set_height(ui_SliderTraction, 11);
    lv_obj_set_x(ui_SliderTraction, -1);
    lv_obj_set_y(ui_SliderTraction, 9);
    lv_obj_set_align(ui_SliderTraction, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SliderTraction, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderTraction, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderTraction, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderTraction, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderTraction, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderTraction, lv_color_hex(0xFB9D16), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderTraction, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SliderTraction, lv_color_hex(0x040000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SliderTraction, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SliderTraction, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SliderTraction, LV_BORDER_SIDE_FULL, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_SliderTraction, lv_color_hex(0x7F7D7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_SliderTraction, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_SliderTraction, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_SliderTraction, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_SliderTraction, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SliderTraction, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SliderTraction, 245, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_SliderTraction, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SliderTraction, 5, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SliderTraction, 30, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SliderTraction, 30, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderTraction, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderTraction,
                                                                                                     lv_obj_get_style_pad_right(ui_SliderTraction, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelTractionValue = lv_label_create(ui_PanelTractionCntrl);
    lv_obj_set_width(ui_LabelTractionValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTractionValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTractionValue, -12);
    lv_obj_set_y(ui_LabelTractionValue, -51);
    lv_obj_set_align(ui_LabelTractionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTractionValue, "...");
    lv_obj_remove_flag(ui_LabelTractionValue,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelTractionValue, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValetPanel = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_ValetPanel, 516);
    lv_obj_set_height(ui_ValetPanel, 195);
    lv_obj_set_x(ui_ValetPanel, 149);
    lv_obj_set_y(ui_ValetPanel, 118);
    lv_obj_set_align(ui_ValetPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ValetPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ValetPanel, lv_color_hex(0x496F8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValetPanel, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTraction1 = lv_label_create(ui_ValetPanel);
    lv_obj_set_width(ui_LabelTraction1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTraction1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTraction1, -66);
    lv_obj_set_y(ui_LabelTraction1, 9);
    lv_obj_set_align(ui_LabelTraction1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTraction1, "Valet Limiter");
    lv_obj_remove_flag(ui_LabelTraction1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelTraction1, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValetSwitch = lv_switch_create(ui_ValetPanel);
    lv_obj_set_width(ui_ValetSwitch, 132);
    lv_obj_set_height(ui_ValetSwitch, 177);
    lv_obj_set_x(ui_ValetSwitch, 89);
    lv_obj_set_y(ui_ValetSwitch, 4);
    lv_obj_set_align(ui_ValetSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ValetSwitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValetSwitch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_ValetSwitch, &ui_img_valet_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_ValetSwitch, &ui_img_valet_on_png, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_opa(ui_ValetSwitch, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_ValetSwitch, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ValetSwitch, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_ValetSwitch, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ValetSwitch, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_PanelScramble = lv_obj_create(ui_ControlPanel);
    lv_obj_set_width(ui_PanelScramble, 302);
    lv_obj_set_height(ui_PanelScramble, 195);
    lv_obj_set_x(ui_PanelScramble, -276);
    lv_obj_set_y(ui_PanelScramble, 117);
    lv_obj_set_align(ui_PanelScramble, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelScramble, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelScramble, lv_color_hex(0x496F8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelScramble, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnScramble = lv_button_create(ui_PanelScramble);
    lv_obj_set_width(ui_BtnScramble, 100);
    lv_obj_set_height(ui_BtnScramble, 100);
    lv_obj_set_x(ui_BtnScramble, 76);
    lv_obj_set_y(ui_BtnScramble, -40);
    lv_obj_set_align(ui_BtnScramble, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_BtnScramble, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_BtnScramble, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnScramble, lv_color_hex(0xD00000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnScramble, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BtnScramble, &ui_img_button_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnScramble, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnScramble, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnScramble, 25, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnScramble, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelScramble = lv_label_create(ui_PanelScramble);
    lv_obj_set_width(ui_LabelScramble, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScramble, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScramble, -1);
    lv_obj_set_y(ui_LabelScramble, 67);
    lv_obj_set_align(ui_LabelScramble, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScramble, "Scramble\n   Boost");
    lv_obj_remove_flag(ui_LabelScramble,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_LabelScramble, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_button_create(ui_ControlPanel);
    lv_obj_set_width(ui_Button5, 408);
    lv_obj_set_height(ui_Button5, 63);
    lv_obj_set_x(ui_Button5, 135);
    lv_obj_set_y(ui_Button5, -211);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button5, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

}

void ui_Screen6_screen_destroy(void)
{
    if(ui_Screen6) lv_obj_del(ui_Screen6);

    // NULL screen variables
    ui_Screen6 = NULL;
    ui_ControlPanel = NULL;
    ui_BoostContainer = NULL;
    ui_RowStreet = NULL;
    ui_LightStreet = NULL;
    ui_LabelStreet = NULL;
    ui_BtnStreet = NULL;
    ui_RowSport = NULL;
    ui_LightSport = NULL;
    ui_LabelSport = NULL;
    ui_BtnSport = NULL;
    ui_RowRace = NULL;
    ui_LightRace = NULL;
    ui_LabelRace = NULL;
    ui_BtnRace = NULL;
    ui_LabelBOOSTMODE = NULL;
    ui_LabelCONTROLHUB = NULL;
    ui_PanelTractionCntrl = NULL;
    ui_LabelTC = NULL;
    ui_SliderTraction = NULL;
    ui_LabelTractionValue = NULL;
    ui_ValetPanel = NULL;
    ui_LabelTraction1 = NULL;
    ui_ValetSwitch = NULL;
    ui_PanelScramble = NULL;
    ui_BtnScramble = NULL;
    ui_LabelScramble = NULL;
    ui_Button5 = NULL;

}
