// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern void ui_event_Dropdown6(lv_event_t * e);
extern lv_obj_t * ui_Dropdown6;
extern lv_obj_t * ui_Slot6;
extern void ui_event_Dropdown7(lv_event_t * e);
extern lv_obj_t * ui_Dropdown7;
extern lv_obj_t * ui_Slot7;
extern void ui_event_Dropdown8(lv_event_t * e);
extern lv_obj_t * ui_Dropdown8;
extern lv_obj_t * ui_Slot8;
extern void ui_event_Dropdown9(lv_event_t * e);
extern lv_obj_t * ui_Dropdown9;
extern lv_obj_t * ui_Slot9;
extern void ui_event_Dropdown10(lv_event_t * e);
extern lv_obj_t * ui_Dropdown10;
extern lv_obj_t * ui_Slot10;
extern lv_obj_t * ui_VSS1;
extern lv_obj_t * ui_speedunit2;
extern lv_obj_t * ui_Fuel1;
extern lv_obj_t * ui_FUELBAR1;
extern lv_obj_t * ui_FUEL1;
extern lv_obj_t * ui_GEAR3;
extern lv_obj_t * ui_Chart3;
extern lv_obj_t * ui_Chart3_Xaxis;
extern lv_obj_t * ui_Chart3_Yaxis1;
extern lv_obj_t * ui_Chart3_Yaxis2;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

