// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Slot1 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
lv_obj_t * ui_Slot2 = NULL;
lv_obj_t * ui_Dropdown3 = NULL;
lv_obj_t * ui_Slot3 = NULL;
lv_obj_t * ui_Dropdown4 = NULL;
lv_obj_t * ui_Slot4 = NULL;
lv_obj_t * ui_Dropdown5 = NULL;
lv_obj_t * ui_Slot5 = NULL;
lv_obj_t * ui_rpm1k = NULL;
lv_obj_t * ui_rpm2k = NULL;
lv_obj_t * ui_rpm3k = NULL;
lv_obj_t * ui_rpm4k = NULL;
lv_obj_t * ui_rpm5k = NULL;
lv_obj_t * ui_rpm6k = NULL;
lv_obj_t * ui_rpm7k = NULL;
lv_obj_t * ui_rpm8k = NULL;
lv_obj_t * ui_RPMBAR1 = NULL;
lv_obj_t * ui_VSS = NULL;
lv_obj_t * ui_speedunit1 = NULL;
lv_obj_t * ui_GEAR1 = NULL;
lv_obj_t * ui_GEAR2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_LTURN = NULL;
lv_obj_t * ui_RTURN = NULL;
lv_obj_t * ui_LOWFUEL = NULL;
lv_obj_t * ui_PARKING = NULL;
lv_obj_t * ui_CASTWIFI = NULL;
lv_obj_t * ui_StreetName = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_weatherLabel = NULL;
lv_obj_t * ui_weatherImage = NULL;
lv_obj_t * ui_LabelMaxSpeedLimit = NULL;
lv_obj_t * ui_LOWOIL = NULL;
lv_obj_t * ui_FUELBAR3 = NULL;
lv_obj_t * ui_FUEL = NULL;
lv_obj_t * ui_FuelLevelLabel = NULL;
lv_obj_t * ui_MainAlertPanel = NULL;
lv_obj_t * ui_MainAlertText = NULL;
lv_obj_t * ui_PanelLaunch = NULL;
lv_obj_t * ui_LabelLaunchReady = NULL;
lv_obj_t * ui_LabelLaunchBoost = NULL;
lv_obj_t * ui_LabelLaunchTitle = NULL;
lv_obj_t * ui_Slip = NULL;
lv_obj_t * ui_Button2 = NULL;
// event funtions
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Screen8, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen8_screen_init);
    }
}

void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot(e);
    }
}

void ui_event_Dropdown2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot(e);
    }
}

void ui_event_Dropdown3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot(e);
    }
}

void ui_event_Dropdown4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot(e);
    }
}

void ui_event_Dropdown5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        updateSlot(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Screen6, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen6_screen_init);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x050500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Screen1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_road2_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 400
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 160
    lv_obj_set_x(ui_Image2, 5);
    lv_obj_set_y(ui_Image2, 67);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_Dropdown1, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown1, "Lambda A\nAfr Target\nAfr\nLambda Corr %\nTotal F Corr %\nBoost Tar");
    lv_obj_set_width(ui_Dropdown1, 190);
    lv_obj_set_height(ui_Dropdown1, 42);
    lv_obj_set_x(ui_Dropdown1, -412);
    lv_obj_set_y(ui_Dropdown1, 208);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown1, lv_color_hex(0xA4B0B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown1, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown1, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Dropdown1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Dropdown1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown1, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0x030303),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown1), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xA4B0B4),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_dropdown_get_list(ui_Dropdown1), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown1), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown1), 75,  LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(lv_dropdown_get_list(ui_Dropdown1), true,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Slot1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot1, -410);
    lv_obj_set_y(ui_Slot1, 258);
    lv_obj_set_align(ui_Slot1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot1, "");
    lv_obj_remove_flag(ui_Slot1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot1, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown2 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_Dropdown2, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown2,
                            "Oil Press kPa\nFuel Press kPa\nBoost kPa\nUser CH1\nUser CH2\nUser CH3\nUser CH4\nUser CH5\nUser CH6");
    lv_obj_set_width(ui_Dropdown2, 193);
    lv_obj_set_height(ui_Dropdown2, 53);
    lv_obj_set_x(ui_Dropdown2, -219);
    lv_obj_set_y(ui_Dropdown2, 201);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown2, lv_color_hex(0xA4B0B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown2, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown2, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown2, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown2, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown2, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown2, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown2), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0xA4B0B4),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown2), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown2), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown2), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Slot2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot2, -201);
    lv_obj_set_y(ui_Slot2, 256);
    lv_obj_set_align(ui_Slot2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot2, "");
    lv_obj_remove_flag(ui_Slot2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot2, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown3 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_Dropdown3, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown3,
                            "ECU Logging\nError Codes\nFuel Tank\nUser CH7\nUser CH8\nUser CH9\nUser CH10\nUser CH11\nUser CH12");
    lv_obj_set_width(ui_Dropdown3, 240);
    lv_obj_set_height(ui_Dropdown3, 53);
    lv_obj_set_x(ui_Dropdown3, 0);
    lv_obj_set_y(ui_Dropdown3, 201);
    lv_obj_set_align(ui_Dropdown3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown3, lv_color_hex(0xA4B0B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown3, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown3, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown3, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown3, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown3, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown3), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0xA4B0B4),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown3), 225,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown3), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown3), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Slot3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot3, 6);
    lv_obj_set_y(ui_Slot3, 257);
    lv_obj_set_align(ui_Slot3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot3, "");
    lv_obj_remove_flag(ui_Slot3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot3, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown4 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_Dropdown4, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown4, "Coolant °C\nIat Temp °C\nCPU Temp °C\nThrottle%\nBaro kPa");
    lv_obj_set_width(ui_Dropdown4, 193);
    lv_obj_set_height(ui_Dropdown4, 53);
    lv_obj_set_x(ui_Dropdown4, 218);
    lv_obj_set_y(ui_Dropdown4, 201);
    lv_obj_set_align(ui_Dropdown4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown4, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown4, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown4, lv_color_hex(0xA4B0B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown4, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown4, lv_color_hex(0xFC0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown4, -3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Dropdown4, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown4, lv_color_hex(0x808080), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown4, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0x050505),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown4), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0xA4B0B4),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown4), 220,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown4), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown4), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Slot4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot4, 208);
    lv_obj_set_y(ui_Slot4, 256);
    lv_obj_set_align(ui_Slot4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot4, "");
    lv_obj_remove_flag(ui_Slot4, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot4, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown5 = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_dir(ui_Dropdown5, LV_DIR_TOP);
    lv_dropdown_set_options(ui_Dropdown5, "Battery V+\nRev Limiter\nBoost Duty %");
    lv_obj_set_width(ui_Dropdown5, 190);
    lv_obj_set_height(ui_Dropdown5, 42);
    lv_obj_set_x(ui_Dropdown5, 412);
    lv_obj_set_y(ui_Dropdown5, 208);
    lv_obj_set_align(ui_Dropdown5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_Dropdown5, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Dropdown5, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dropdown5, lv_color_hex(0xA4B0B4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dropdown5, 220, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Dropdown5, lv_color_hex(0x4A4848), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Dropdown5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Dropdown5, -3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Dropdown5, lv_color_hex(0x090101), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Dropdown5, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0x040404),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Dropdown5), &lv_font_montserrat_22,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0xA4B0B4),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown5), 220,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_Dropdown5), lv_color_hex(0xFFFFFF),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_Dropdown5), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Slot5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Slot5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Slot5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Slot5, 407);
    lv_obj_set_y(ui_Slot5, 260);
    lv_obj_set_align(ui_Slot5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Slot5, "");
    lv_obj_remove_flag(ui_Slot5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_Slot5, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Slot5, lv_color_hex(0x1CDB41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Slot5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm1k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm1k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm1k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm1k, -296);
    lv_obj_set_y(ui_rpm1k, -255);
    lv_obj_set_align(ui_rpm1k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm1k, "1");
    lv_obj_remove_flag(ui_rpm1k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm1k, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm1k, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm1k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm2k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm2k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm2k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm2k, -183);
    lv_obj_set_y(ui_rpm2k, -255);
    lv_obj_set_align(ui_rpm2k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm2k, "2");
    lv_obj_remove_flag(ui_rpm2k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm2k, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm2k, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm2k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm3k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm3k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm3k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm3k, -76);
    lv_obj_set_y(ui_rpm3k, -255);
    lv_obj_set_align(ui_rpm3k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm3k, "3");
    lv_obj_remove_flag(ui_rpm3k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm3k, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm3k, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm3k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm4k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm4k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm4k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm4k, 34);
    lv_obj_set_y(ui_rpm4k, -255);
    lv_obj_set_align(ui_rpm4k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm4k, "4");
    lv_obj_remove_flag(ui_rpm4k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm4k, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm4k, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm4k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm5k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm5k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm5k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm5k, 148);
    lv_obj_set_y(ui_rpm5k, -255);
    lv_obj_set_align(ui_rpm5k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm5k, "5");
    lv_obj_remove_flag(ui_rpm5k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm5k, lv_color_hex(0x909090), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm5k, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm5k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm6k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm6k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm6k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm6k, 256);
    lv_obj_set_y(ui_rpm6k, -255);
    lv_obj_set_align(ui_rpm6k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm6k, "6");
    lv_obj_remove_flag(ui_rpm6k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm6k, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm6k, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm6k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm7k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm7k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm7k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm7k, 368);
    lv_obj_set_y(ui_rpm7k, -255);
    lv_obj_set_align(ui_rpm7k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm7k, "7");
    lv_obj_remove_flag(ui_rpm7k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm7k, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm7k, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm7k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpm8k = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpm8k, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpm8k, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpm8k, 477);
    lv_obj_set_y(ui_rpm8k, -255);
    lv_obj_set_align(ui_rpm8k, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rpm8k, "8");
    lv_obj_remove_flag(ui_rpm8k, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_rpm8k, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpm8k, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpm8k, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RPMBAR1 = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_RPMBAR1, 500, 8000);
    lv_bar_set_value(ui_RPMBAR1, 8000, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_RPMBAR1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_RPMBAR1, 830);
    lv_obj_set_height(ui_RPMBAR1, 6);
    lv_obj_set_x(ui_RPMBAR1, 67);
    lv_obj_set_y(ui_RPMBAR1, -236);
    lv_obj_set_align(ui_RPMBAR1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_RPMBAR1, -5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBAR1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBAR1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_RPMBAR1, 2, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RPMBAR1, lv_color_hex(0x3592DF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RPMBAR1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_RPMBAR1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_RPMBAR1,
                                                                                              lv_obj_get_style_pad_right(ui_RPMBAR1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_VSS = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_VSS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VSS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VSS, 4);
    lv_obj_set_y(ui_VSS, -16);
    lv_obj_set_align(ui_VSS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VSS, "0");
    lv_obj_remove_flag(ui_VSS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_VSS, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VSS, &ui_font_Rubik150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_speedunit1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_speedunit1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_speedunit1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_speedunit1, 2);
    lv_obj_set_y(ui_speedunit1, 74);
    lv_obj_set_align(ui_speedunit1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speedunit1, "km/h");
    lv_obj_remove_flag(ui_speedunit1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_speedunit1, lv_color_hex(0xA7A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_speedunit1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_speedunit1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GEAR1 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_GEAR1, "N\n1\n2\n3\n4\n5", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_GEAR1, 118);
    lv_obj_set_width(ui_GEAR1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_GEAR1, -429);
    lv_obj_set_y(ui_GEAR1, -219);
    lv_obj_set_align(ui_GEAR1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GEAR1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_GEAR1, lv_color_hex(0x98FF03), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR1, &ui_font_Rubik130, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GEAR1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GEAR1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_GEAR1, lv_color_hex(0xC4FF0E), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR1, &ui_font_Rubik150, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR1, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR1, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_GEAR2 = lv_roller_create(ui_Screen1);
    lv_roller_set_options(ui_GEAR2, "N\n1\n2\n3\n4\n5", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_GEAR2, 65);
    lv_obj_set_height(ui_GEAR2, 42);
    lv_obj_set_x(ui_GEAR2, -348);
    lv_obj_set_y(ui_GEAR2, -149);
    lv_obj_set_align(ui_GEAR2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GEAR2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_text_color(ui_GEAR2, lv_color_hex(0xBFC0BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR2, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR2, lv_color_hex(0x363535), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_GEAR2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_GEAR2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_GEAR2, lv_color_hex(0xBFC0BD), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_GEAR2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GEAR2, &ui_font_Rubik37, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GEAR2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GEAR2, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 310);
    lv_obj_set_height(ui_Button1, 166);
    lv_obj_set_x(ui_Button1, -3);
    lv_obj_set_y(ui_Button1, -4);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x2E3B7D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LTURN = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_LTURN, &ui_img_left_png);
    lv_obj_set_width(ui_LTURN, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_LTURN, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_LTURN, -200);
    lv_obj_set_y(ui_LTURN, -152);
    lv_obj_set_align(ui_LTURN, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LTURN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_RTURN = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_RTURN, &ui_img_right_png);
    lv_obj_set_width(ui_RTURN, LV_SIZE_CONTENT);   /// 33
    lv_obj_set_height(ui_RTURN, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_RTURN, 200);
    lv_obj_set_y(ui_RTURN, -152);
    lv_obj_set_align(ui_RTURN, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_RTURN, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_LOWFUEL = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_LOWFUEL, &ui_img_lowfuel_png);
    lv_obj_set_width(ui_LOWFUEL, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_LOWFUEL, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_LOWFUEL, 235);
    lv_obj_set_y(ui_LOWFUEL, 104);
    lv_obj_set_align(ui_LOWFUEL, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LOWFUEL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_PARKING = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_PARKING, &ui_img_parking_brake_png);
    lv_obj_set_width(ui_PARKING, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_PARKING, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_PARKING, -440);
    lv_obj_set_y(ui_PARKING, 126);
    lv_obj_set_align(ui_PARKING, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PARKING, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_scale(ui_PARKING, 225);
    lv_obj_set_style_radius(ui_PARKING, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CASTWIFI = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_CASTWIFI, &ui_img_cast_32__png);
    lv_obj_set_width(ui_CASTWIFI, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_CASTWIFI, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_CASTWIFI, -449);
    lv_obj_set_y(ui_CASTWIFI, -42);
    lv_obj_set_align(ui_CASTWIFI, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CASTWIFI, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_StreetName = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_StreetName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StreetName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StreetName, 30);
    lv_obj_set_y(ui_StreetName, -162);
    lv_obj_set_align(ui_StreetName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StreetName, "");
    lv_obj_remove_flag(ui_StreetName, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_StreetName, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button7, 193);
    lv_obj_set_height(ui_Button7, 93);
    lv_obj_set_x(ui_Button7, 402);
    lv_obj_set_y(ui_Button7, -122);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button7, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                       LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherLabel = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_weatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherLabel, 25);
    lv_obj_set_y(ui_weatherLabel, 7);
    lv_obj_set_align(ui_weatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherLabel, "\"--\"");
    lv_obj_remove_flag(ui_weatherLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_weatherLabel, lv_color_hex(0xD6D7D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherImage = lv_image_create(ui_Button7);
    lv_image_set_src(ui_weatherImage, &ui_img_cloud_png);
    lv_obj_set_width(ui_weatherImage, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_weatherImage, LV_SIZE_CONTENT);    /// 24
    lv_obj_set_x(ui_weatherImage, 44);
    lv_obj_set_y(ui_weatherImage, -29);
    lv_obj_set_align(ui_weatherImage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_weatherImage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_LabelMaxSpeedLimit = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelMaxSpeedLimit, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_LabelMaxSpeedLimit, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_LabelMaxSpeedLimit, 0);
    lv_obj_set_y(ui_LabelMaxSpeedLimit, -123);
    lv_obj_set_align(ui_LabelMaxSpeedLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMaxSpeedLimit, "Searching for Satellite...");
    lv_obj_remove_flag(ui_LabelMaxSpeedLimit,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelMaxSpeedLimit, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMaxSpeedLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMaxSpeedLimit, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LabelMaxSpeedLimit, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LabelMaxSpeedLimit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LabelMaxSpeedLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LabelMaxSpeedLimit, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LabelMaxSpeedLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LabelMaxSpeedLimit, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_LabelMaxSpeedLimit, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_LabelMaxSpeedLimit, lv_color_hex(0xFBFAFA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_LabelMaxSpeedLimit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelMaxSpeedLimit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelMaxSpeedLimit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelMaxSpeedLimit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelMaxSpeedLimit, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LOWOIL = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_LOWOIL, &ui_img_3103_png);
    lv_obj_set_width(ui_LOWOIL, LV_SIZE_CONTENT);   /// 36
    lv_obj_set_height(ui_LOWOIL, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_LOWOIL, -445);
    lv_obj_set_y(ui_LOWOIL, 34);
    lv_obj_set_align(ui_LOWOIL, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LOWOIL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_FUELBAR3 = lv_bar_create(ui_Screen1);
    lv_obj_set_width(ui_FUELBAR3, 255);
    lv_obj_set_height(ui_FUELBAR3, 2);
    lv_obj_set_x(ui_FUELBAR3, 352);
    lv_obj_set_y(ui_FUELBAR3, 132);
    lv_obj_set_align(ui_FUELBAR3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_FUELBAR3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_obj_set_style_radius(ui_FUELBAR3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUELBAR3, lv_color_hex(0x4F4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUELBAR3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FUELBAR3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUELBAR3, lv_color_hex(0x0BF438), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUELBAR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_FUELBAR3, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_FUELBAR3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_FUELBAR3, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_FUELBAR3, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_FUELBAR3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_FUELBAR3,
                                                                                               lv_obj_get_style_pad_right(ui_FUELBAR3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_FUEL = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FUEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL, 398);
    lv_obj_set_y(ui_FUEL, 113);
    lv_obj_set_align(ui_FUEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FUEL, "");
    lv_obj_remove_flag(ui_FUEL, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_FUEL, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FuelLevelLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_FuelLevelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FuelLevelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FuelLevelLabel, 306);
    lv_obj_set_y(ui_FuelLevelLabel, 117);
    lv_obj_set_align(ui_FuelLevelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FuelLevelLabel, "Fuel");
    lv_obj_remove_flag(ui_FuelLevelLabel,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_FuelLevelLabel, lv_color_hex(0xA7A4A4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FuelLevelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FuelLevelLabel, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertPanel = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_MainAlertPanel, 194);
    lv_obj_set_height(ui_MainAlertPanel, 37);
    lv_obj_set_x(ui_MainAlertPanel, 400);
    lv_obj_set_y(ui_MainAlertPanel, 3);
    lv_obj_set_align(ui_MainAlertPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MainAlertPanel,
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_MainAlertPanel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainAlertPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainAlertPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainAlertText = lv_label_create(ui_MainAlertPanel);
    lv_obj_set_width(ui_MainAlertText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainAlertText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainAlertText, -1);
    lv_obj_set_y(ui_MainAlertText, 0);
    lv_obj_set_align(ui_MainAlertText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainAlertText, "Check Engine");
    lv_obj_remove_flag(ui_MainAlertText,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_MainAlertText, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLaunch = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelLaunch, 420);
    lv_obj_set_height(ui_PanelLaunch, 244);
    lv_obj_set_x(ui_PanelLaunch, -125);
    lv_obj_set_y(ui_PanelLaunch, 10);
    lv_obj_set_align(ui_PanelLaunch, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelLaunch, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_PanelLaunch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_PanelLaunch, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLaunch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLaunch, 235, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLaunch, lv_color_hex(0xFF2424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLaunch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelLaunch, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_PanelLaunch, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLaunchReady = lv_label_create(ui_PanelLaunch);
    lv_obj_set_width(ui_LabelLaunchReady, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLaunchReady, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLaunchReady, 9);
    lv_obj_set_y(ui_LabelLaunchReady, 12);
    lv_obj_set_align(ui_LabelLaunchReady, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLaunchReady, "");
    lv_obj_remove_flag(ui_LabelLaunchReady,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelLaunchReady, lv_color_hex(0x31E131), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLaunchReady, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLaunchReady, &ui_font_orbitron60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLaunchBoost = lv_label_create(ui_PanelLaunch);
    lv_obj_set_width(ui_LabelLaunchBoost, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLaunchBoost, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLaunchBoost, 1);
    lv_obj_set_y(ui_LabelLaunchBoost, 77);
    lv_obj_set_align(ui_LabelLaunchBoost, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLaunchBoost, "0.0 psi");
    lv_obj_remove_flag(ui_LabelLaunchBoost,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelLaunchBoost, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLaunchBoost, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLaunchBoost, &ui_font_orbitron40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLaunchTitle = lv_label_create(ui_PanelLaunch);
    lv_obj_set_width(ui_LabelLaunchTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLaunchTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLaunchTitle, -5);
    lv_obj_set_y(ui_LabelLaunchTitle, -90);
    lv_obj_set_align(ui_LabelLaunchTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelLaunchTitle, "LAUNCH  ACTIVE");
    lv_obj_remove_flag(ui_LabelLaunchTitle,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_LabelLaunchTitle, lv_color_hex(0xF5BF1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelLaunchTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelLaunchTitle, &ui_font_orbitron25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slip = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Slip, &ui_img_slip_png);
    lv_obj_set_width(ui_Slip, LV_SIZE_CONTENT);   /// 65
    lv_obj_set_height(ui_Slip, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_Slip, -217);
    lv_obj_set_y(ui_Slip, 40);
    lv_obj_set_align(ui_Slip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Slip, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Slip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 338);
    lv_obj_set_height(ui_Button2, 71);
    lv_obj_set_x(ui_Button2, 3);
    lv_obj_set_y(ui_Button2, -133);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown2, ui_event_Dropdown2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown3, ui_event_Dropdown3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown4, ui_event_Dropdown4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Dropdown5, ui_event_Dropdown5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Image2 = NULL;
    ui_Dropdown1 = NULL;
    ui_Slot1 = NULL;
    ui_Dropdown2 = NULL;
    ui_Slot2 = NULL;
    ui_Dropdown3 = NULL;
    ui_Slot3 = NULL;
    ui_Dropdown4 = NULL;
    ui_Slot4 = NULL;
    ui_Dropdown5 = NULL;
    ui_Slot5 = NULL;
    ui_rpm1k = NULL;
    ui_rpm2k = NULL;
    ui_rpm3k = NULL;
    ui_rpm4k = NULL;
    ui_rpm5k = NULL;
    ui_rpm6k = NULL;
    ui_rpm7k = NULL;
    ui_rpm8k = NULL;
    ui_RPMBAR1 = NULL;
    ui_VSS = NULL;
    ui_speedunit1 = NULL;
    ui_GEAR1 = NULL;
    ui_GEAR2 = NULL;
    ui_Button1 = NULL;
    ui_LTURN = NULL;
    ui_RTURN = NULL;
    ui_LOWFUEL = NULL;
    ui_PARKING = NULL;
    ui_CASTWIFI = NULL;
    ui_StreetName = NULL;
    ui_Button7 = NULL;
    ui_weatherLabel = NULL;
    ui_weatherImage = NULL;
    ui_LabelMaxSpeedLimit = NULL;
    ui_LOWOIL = NULL;
    ui_FUELBAR3 = NULL;
    ui_FUEL = NULL;
    ui_FuelLevelLabel = NULL;
    ui_MainAlertPanel = NULL;
    ui_MainAlertText = NULL;
    ui_PanelLaunch = NULL;
    ui_LabelLaunchReady = NULL;
    ui_LabelLaunchBoost = NULL;
    ui_LabelLaunchTitle = NULL;
    ui_Slip = NULL;
    ui_Button2 = NULL;

}
